### ISSUE TITLE
LinkedAuthorizationFailed

### ISSUE THREAD

**Issue by kelpius** [usri/deploy_DevOps_Server_AzureSQL#1]
Each time I attempt to run the deployment, I receive the following during 'Write VirtualMachines': 

"The client has permission to perform action 'Microsoft.Compute/images/read' on scope '(MY_SUBSCRIPTION)/(MY_RESOURCEGROUP)/(MY_VM)', however the current tenant '(MY_KEYVAULT)' is not authorized to access linked subscription '(ID from template script)'"

I've tried various formatting on the secret name/value in the Key Vault, and opened up access controls where that might have been the issue, but now I'm at a loss. All the referenced resources were created from scratch for the purpose of getting a test repository running, and the only template parameters left unchanged are "Database Names" and "File Uris". 

Any insight would be greatly appreciated.

**Comment by ExchMaster** [comment]
@kelpius ,

Looks like there are multiple issues, there is a hard link for the subscription and vault, and the read me file needs to be updated to properly point out the necessity of creating the actual base level image.

I'm going to take some time to actually update the template to remove the hard links which was simply bad on my part and also update the actual markdown to make it a little easier for people to follow.  

Thank you for bringing this up, it might be a couple days before I merge changes.     That should resolve your issues.

Thank you

**Comment by kelpius** [comment]
@ExchMaster 

Thanks for the clarification. Today I was able to fully deploy, the only real issue was accessing the configureSQL script even with the correct subnet endpoints etc. I ended up just running those commands manually on the server VM, and that looked like the final step anyway, everything seems to be working. Thanks again!
